### ISSUE TITLE
README instructions do not match sample

### ISSUE THREAD

**Issue by inhaledesign** [blipinsk/disable-animations-rule#2]
In the README, there's directoins to use @ClassRule:

```
@ClassRule
public static DisableAnimationsRule animationsRule = new DisableAnimationsRule();
```

But in the code sample, the code uses an instance level @Rule
https://github.com/blipinsk/disable-animations-rule/blob/f3bd9c934d4b139200ee97e1b2c108a2d122d7ff/sample/src/androidTest/java/com/bartoszlipinski/disableanimationsrule/sample/activity/MainActivityTest.java#L18-L25

This is maybe a minor point, but noticing the discrepancy I am left wondering if there is a reason to prefer one over the other?

**Comment by blipinsk** [comment]
`@ClassRule` should be used in most cases as it would make your tests better in terms of performance. You would see the difference if you had multiple `@Test` functions in your class.

E.g. it would work as following
1. Using `@ClassRule` (executed once for the class)
  * Disabling animations
  * executing `@Test` # 1
  * executing `@Test` # 2
  * executing `@Test` # 3
  * Enabling animations

2. Using `@Rule` (executed once for every test)
  * Disabling animations
  * executing `@Test` # 1
  * Enabling animations
  * Disabling animations
  * executing `@Test` # 2
  * Enabling animations
  * Disabling animations
  * executing `@Test` # 3
  * Enabling animations

I used `@Rule` in the sample because... ¯\_(ツ)_/¯ 
I might change it at some point if you found it confusing.

**Comment by blipinsk** [comment]
@inhaledesign did you find my explanation informative enough?

**Comment by inhaledesign** [comment]
Hey, sorry for not replying.  Yeah, the explanation was very clear, thank you.

**Comment by blipinsk** [comment]
No worries, cheers.
